#!/usr/bin/env python3
"""Copies ConfigManipulation::toggle_print_fff_options() out of the desktop GUI sources.

The function holds OrcaSlicer's rules for which process options are enabled/visible depending on
other values (e.g. support options greyed out while supports are off). It only needs a handful of
GUI services, which core/jni/OptionToggles.hpp provides as stand-ins, so the body is compiled
unchanged and follows upstream automatically.

usage: extract_option_toggles.py <ConfigManipulation.cpp> <output.cpp>
"""
import sys
from pathlib import Path

SIGNATURE = "void ConfigManipulation::toggle_print_fff_options("


def extract(source: str) -> str:
    start = source.index(SIGNATURE)
    brace = source.index("{", start)
    depth, i = 0, brace
    in_string = in_char = False
    while True:
        c = source[i]
        if c == '"' and not in_char and source[i - 1] != "\\":
            in_string = not in_string
        elif c == "'" and not in_string and source[i - 1] != "\\":
            in_char = not in_char
        elif not in_string and not in_char:
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    return source[start:i + 1]
        i += 1


def main() -> None:
    src, out = Path(sys.argv[1]), Path(sys.argv[2])
    body = extract(src.read_text(encoding="utf-8"))
    out.write_text(
        "// Generated by android/scripts/extract_option_toggles.py from\n"
        f"// {src.name} - do not edit.\n"
        '#include "OptionToggles.hpp"\n\n'
        "namespace Slic3r { namespace GUI {\n\n"
        + body + "\n\n}} // namespace Slic3r::GUI\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
