#!/usr/bin/env python3
"""Copies the wxWidgets-free part of src/slic3r/Utils/ColorSpaceConvert.cpp.

libslic3r's FlushVolCalc uses RGB2HSV() & co., which upstream only builds into the GUI. The file's
colour math does not need wx; only the wxColour helpers at its end do, so they are cut off.

usage: extract_color_space.py <ColorSpaceConvert.cpp> <output.cpp>
"""
import sys
from pathlib import Path

src, out = Path(sys.argv[1]), Path(sys.argv[2])
text = src.read_text(encoding="utf-8")
text = text[: text.index("std::string color_to_string(const wxColour")]
lines = [l for l in text.splitlines() if "#include <wx/" not in l and '#include "ColorSpaceConvert.hpp"' not in l]
out.write_text(
    "// Generated by android/scripts/extract_color_space.py - do not edit.\n"
    "#include <string>\n#include <tuple>\n\n" + "\n".join(lines) + "\n",
    encoding="utf-8",
)
