#!/usr/bin/env python3
"""Builds the Android copy of OrcaSlicer's plugin capability config store.

    extract_plugin_config.py <src/slic3r/plugin/PluginConfig.cpp> <output.cpp>

PluginConfig.cpp keeps the GUI-free config store (load/save, preset overrides, the get_config /
save_config calls plugins make) together with the JSON responses of the wxWidgets config dialog.
This keeps everything up to the dialog responses, drops the GUI includes, and asks the Android
runtime for the active preset bundle instead of the wx application. Any anchor that is missing
after an upstream change fails the build instead of producing a silently different file.
"""
import re
import sys

src, out = sys.argv[1], sys.argv[2]
text = open(src, encoding="utf-8").read()


def require(cond, what):
    if not cond:
        sys.exit(f"extract_plugin_config: {what} not found in {src}; update this script")


lines = [l for l in text.split("\n") if not re.match(r"\s*#include\s*<(slic3r/GUI/|wx/)", l)]
text = "\n".join(lines)

body = re.compile(r"(const PresetBundle\* active_preset_bundle\(\)\s*\{).*?(\n\})", re.S)
require(body.search(text), "active_preset_bundle()")
text = body.sub(lambda m: m.group(1) + "\n    return android_active_preset_bundle();" + m.group(2), text, count=1)

anchor = "\nnamespace Slic3r {\n"
require(anchor in text, "namespace Slic3r")
text = text.replace(anchor, anchor + "\n// Android: the preset bundle of the running engine (AndroidPluginHost.cpp).\nconst PresetBundle* android_active_preset_bundle();\n", 1)

cut = text.find("\nnlohmann::json PluginConfig::capabilities_payload(")
require(cut >= 0, "PluginConfig::capabilities_payload")
text = text[:cut] + "\n\n} // namespace Slic3r\n"

with open(out, "w", encoding="utf-8") as f:
    f.write("// Generated by android/scripts/extract_plugin_config.py from src/slic3r/plugin/PluginConfig.cpp.\n")
    f.write(text)
